apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-ao-ds
  namespace: kube-system
  labels:
    daemon: kube-ao-ds
spec:
  template:
    metadata:
      name: kube-ao-ds
      labels:
        daemon: kube-ao-ds
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kube-ao-ds
        image: 'appoptics/kube-ao:v0.2'
        imagePullPolicy: Always
        env:
          - name: APPOPTICS_TOKEN
            value: 'APPOPTICS_TOKEN'
          - name: APPOPTICS_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: APPOPTICS_ENABLE_DOCKER
            value: 'true'
          - name: HOST_PROC
            value: '/host/proc'
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: cgroup
            mountPath: /sys/fs/cgroup
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
