kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: kube-ao
  namespace: <your-namespace-here>
  labels:
    app: kube-ao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ao
  template:
    metadata:
      labels:
        app: kube-ao
    spec:
      serviceAccountName: kube-ao-serviceaccount
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: kube-ao
          image: 'appoptics/kube-ao:v0.1'
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: kube-ao-config
              readOnly: true
              mountPath: /opt/appoptics/etc/config.yaml
              subPath: config.yaml
      volumes:
        - name: kube-ao-config
          secret:
            secretName: kube-ao-config-secret
            items:
              - key: appoptics-config.yaml
                path: config.yaml
            defaultMode: 420
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
