apiVersion: v1
kind: List
items:
# Service Account for kube-ao
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: kube-ao-serviceaccount
    namespace: kube-system
# Create ClusterRole that enables kube-ao to access requisite kube-api resources
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: kube-ao-clusterrole
  rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
# Bind the kube-ao-role with the kube-ao-serviceaccount we created above
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: kube-ao-clusterrolebinding
  subjects:
  - kind: ServiceAccount
    name: kube-ao-serviceaccount
    namespace: kube-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kube-ao-clusterrole
