apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-ao-ds
  namespace: <your-namespace-here>
  labels:
    daemon: kube-ao-ds
spec:
  template:
    metadata:
      name: kube-ao-ds
      labels:
        daemon: kube-ao-ds
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      securityContext:
        fsGroup: 233
      containers:
      - name: kube-ao-ds
        image: 'cmrust/kube-ao-ds:v0.1'
        imagePullPolicy: Always
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: cgroup
            mountPath: /sys/fs/cgroup
          - name: kube-ao-ds-config
            readOnly: true
            mountPath: /opt/appoptics/etc/config.yaml
            subPath: config.yaml
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: kube-ao-ds-config
          secret:
            secretName: kube-ao-ds-config-secret
            items:
              - key: appoptics-config.yaml
                path: config.yaml
            defaultMode: 420
