version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Build docker image
          command: docker build .

workflows:
  version: 2
  build:
    jobs:
      - build
